# Generated by Django 5.1.3 on 2024-11-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
